name: egs-win-x64 

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: windows-2022
    steps:
    
      - name: Check out repository
        uses: actions/checkout@v3 

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Build with dotnet
        run: |
          dotnet build examples/sipexamples/sipexamples.sln --configuration Release
          dotnet build examples/webrtcexamples/webrtcexamples.sln --configuration Release
          dotnet build examples/webrtccmdline/webrtccmdline.sln --configuration Release
          dotnet build examples/sipcmdline/sipcmdline.sln --configuration Release
          dotnet build examples/stunserver/stunserver.sln --configuration Release
          dotnet build examples/softphone/sipsorcery.softphone.sln --configuration Release
